### ISSUE TITLE
Is Python 2.6.5 supported?

### ISSUE THREAD

**Issue by Preston-Landers** [python-modernize/python-modernize#138]
I'm trying to use Modernize to help convert a project that is currently using Python 2.6.5.  Using it under that interpreter version produces this error:

```
$ python-modernize -w project.py
Traceback (most recent call last):
  File "//home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/bin/python-modernize", line 9, in <module>
    load_entry_point('modernize==0.5', 'console_scripts', 'python-modernize')()
  File "/home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/lib/python2.6/site-packages/libmodernize/main.py", line 129, in main
    options.nobackups, not options.no_diffs)
  File "/home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/lib/python2.6/lib2to3/main.py", line 32, in __init__
    super(StdoutRefactoringTool, self).__init__(fixers, options, explicit)
  File "/home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/lib/python2.6/lib2to3/refactor.py", line 606, in __init__
    super(MultiprocessRefactoringTool, self).__init__(*args, **kwargs)
  File "/home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/lib/python2.6/lib2to3/refactor.py", line 200, in __init__
    self.pre_order, self.post_order = self.get_fixers()
  File "/home/planders/s/jtdev2/dist/pkg/Linux/xx/pd/Linux/python/lib/python2.6/lib2to3/refactor.py", line 218, in get_fixers
    mod = __import__(fix_mod_path, {}, {}, ["*"])
ImportError: No module named fix_exitfunc
```

It looks like lib2to3 in Python 2.6.5 doesn't include a fixer called fix_exitfunc.

If Modernizer requires a specific version of Python 2, then it should probably indicate that in the prerequisites. 

Maybe I should be using a newer Python interpreter to do this conversion even if we don't plan to ship a product using that version.

**Comment by takluyver** [comment]
Yeah, it supports 2.6 in the result, but you should do the conversion process with the newest version of Python you can conveniently get. I don't see much value in supporting old versions to run the command line developer tool.

**Comment by Preston-Landers** [comment]
Ok that makes sense. Thanks.

**Comment by takluyver** [comment]
Great :-) If you think that's worth explaining in the docs, PRs welcome!
